name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DB_NAME: test
  DBUser: nadermamdouh # Replace with the new MySQL user
  DBPassword: nadermamdouh123@ # Replace with the password for the new MySQL user

jobs:
  run_code_checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Set up MySQL service and create the database with the new user
      - name: Set up MySQL and Create Database
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e "CREATE USER IF NOT EXISTS 'nadermamdouh'@'localhost' IDENTIFIED BY 'nadermamdouh123@';" -uroot -proot
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'nadermamdouh'@'localhost' WITH GRANT OPTION;" -uroot -proot
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS test;" -unadermamdouh -pnadermamdouh123@

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      # Install dependencies
      - name: Install Dependencies
        run: go mod download

      # Run Go tests
      - name: Run Go Tests
        run: go test ./...

      # Run Linter
      - name: Run Go Lint
        run: go vet ./...
