name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DB_NAME: test
  DBUser: root

jobs:
  run_code_checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Set up MySQL service and create the database
      - name: Set up MySQL
        run: |
          sudo service mysql start
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u${{ env.DBUser }} -p${{ secrets.MYSQL_ROOT_PASSWORD }}

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      # Install dependencies
      - name: Install Dependencies
        run: go mod download

      # Run Go tests
      - name: Run Go Tests
        run: go test ./...

      # Run Linter
      - name: Run Go Lint
        run: go vet ./...
