name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DB_NAME: test
  DBUser: nader
  DBPassword: asdf12345@

jobs:
  run_code_checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Set up MySQL service and create the database with the new user
      - name: Set up MySQL and Create Database
        run: |
          sudo service mysql start
          sudo mysql -uroot -proot -e "CREATE USER IF NOT EXISTS '${{ env.DBUser }}'@'localhost' IDENTIFIED BY '${{ env.DBPassword }}';"
          sudo mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO '${{ env.DBUser }}'@'localhost';"
          sudo mysql -uroot -proot -e "FLUSH PRIVILEGES;"
          sudo mysql -u${{ env.DBUser }} -p${{ env.DBPassword }} -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      # Install dependencies
      - name: Install Dependencies
        run: go mod download

      # Run Go tests
      - name: Run Go Tests
        run: go test ./...

      # Run Linter
      - name: Run Go Lint
        run: go vet ./...
